language: node_js

node_js:
  - stable

script: make lint test

addons:
  code_climate:
    repo_token: d929716e703c5fc5f535a9b3f9c800611066d0a66c13bd11c5ad4a221f490db9

after_success:
  - npm install -g istanbul
  - npm install -g codeclimate-test-reporter
  - istanbul cover node_modules/jest/bin/jest.js -- --coverage
  - codeclimate-test-reporter < ./coverage/lcov.info
